kapacitor:
    image: kapacitor:1.5.0
    container_name: kapacitor
    environment:
      KAPACITOR_HOSTNAME: $KAPACITOR_CONTAINER_NAME
      KAPACITOR_INFLUXDB_0_URLS_0: http://opennti_con:8086/
    ports:
      - "9092:9092"
    links:
      - opennti

chronograf:
    image: quay.io/influxdb/chronograf:1.5.0.1
    container_name: $CHRONOGRAF_CONTAINER_NAME
    environment:
      INFLUXDB_URL: http://opennti_con:8086/
      KAPACITOR_URL: http://kapacitor:9092/
    ports:
      - "8888:8888"
    links:
      - opennti

opennti:
  image: $MAIN_IMAGE_NAME:$IMAGE_TAG
  container_name: $MAIN_CONTAINER_NAME
# Uncomment environment to allow anonymous grafana access
# and disable user sign up
  environment:
    - "GF_PATHS_PROVISIONING=/src/provisioning"
#   - "GF_USERS_ALLOW_SIGN_UP=false"
#   - "GF_AUTH_ANONYMOUS_ENABLED=true"
  restart: always
  volumes:
   - ./$LOCAL_DIR_GF_PROVISIONING:/src/provisioning
   - ./$LOCAL_DIR_DASHBOARD:/src/dashboards
   - ./$LOCAL_DIR_DATA:/opt/open-nti/data
   - ./$LOCAL_DIR_LOG:/opt/open-nti/logs
   - ./$LOCAL_DIR_DB_DATA:/data
   - ./$LOCAL_DIR_DB_VAR:/var/lib/influxdb
   - /etc/localtime:/etc/localtime
  ports:
   - "$LOCAL_PORT_STATSD:8125/udp"
   - "$LOCAL_PORT_NGINX:80"
   - "$LOCAL_PORT_GRAFANA:3000"
   - "$LOCAL_PORT_INFLUXDB:8083"
   - "$LOCAL_PORT_INFLUXDB_API:8086"