
input-jti:
  image: juniper/open-nti-input-jti
  container_name: opennti_input_jti
  environment:
   - "INFLUXDB_ADDR=opennti"
   - "OUTPUT_INFLUXDB=true"
   - "OUTPUT_STDOUT=false"
  ports:
   - "$LOCAL_PORT_JTI:50000/udp"
   - "$LOCAL_PORT_ANALYTICSD:50020/udp"
  volumes:
   - /etc/localtime:/etc/localtime
  links:
   - opennti

input-syslog:
  image: juniper/open-nti-input-syslog
  container_name: opennti_input_syslog
  environment:
   - "INFLUXDB_ADDR=opennti"
   - "OUTPUT_INFLUXDB=true"
   - "OUTPUT_STDOUT=false"
  ports:
   - "$LOCAL_PORT_EVENT:6000/udp"
  volumes:
   - /etc/localtime:/etc/localtime
  links:
   - opennti

opennti:
  image: $IMAGE_NAME
  container_name: $CONTAINER_NAME
  volumes:
   - ../$LOCAL_DIR_DASHBOARD:/src/dashboards
   - ../$LOCAL_DIR_DATA:/opt/open-nti/data
   - ../$LOCAL_DIR_LOG:/opt/open-nti/logs
   - ../$LOCAL_DIR_DB:/data
   - /etc/localtime:/etc/localtime
  ports:
   - "$LOCAL_PORT_STATSD:8125/udp"
   - "$LOCAL_PORT_NGINX:80"
   - "$LOCAL_PORT_GRAFANA:3000"
   - "$LOCAL_PORT_INFLUXDB:8083"
   - "$LOCAL_PORT_INFLUXDB_API:8086"
