{
 "title": "evo",
 "tags": [
  "netconf",
  "open-nti",
  "PyEz"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DUT Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mode(\"value_str\") FROM /($host_regex).version/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Routing Engine statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "RE CPU Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$host_regex$/",
       "query": "select 100 - mean(value) from /($host_regex).chassis.routing-engine.*.cpu-idle/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " -100" ], "type": "math" }
        ]
       ],
       "series": "/$host_regex.chassis.routing-engine.*.cpu-idle/"
      }
     ]
    },
    {
     "title": "RE - Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).chassis.routing-engine.*.memory-buffer-utilization/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.chassis.routing-engine.*.memory-buffer-utilization/"
      }
     ]
    }
   ]
  },
  {
   "title": "Routing Table Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active routes (inet.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.0.actives/"
      }
     ]
    },
    {
     "title": "Total routes (inet.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.0.routes/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.0.routes/"
      }
     ]
    },
    {
     "title": "Active routes (inet6.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet6.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.routes/"
      }
     ]
    },
    {
     "title": "Total routes (inet6.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet6.0.routes/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.routes/"
      }
     ]
    },
    {
     "title": "Actives routes (bgp.l3vpn.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.bgp.l3vpn.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.actives/"
      }
     ]
    },
    {
     "title": "Total routes (bgp.l3vpn.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.bgp.l3vpn.0.routes/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.routes/"
      }
     ]
    },
    {
     "title": "Active routes (inet.3)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.3.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.actives/"
      }
     ]
    },
    {
     "title": "Total routes (inet.3)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.3.routes/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.routes/"
      }
     ]
    },
    {
     "title": "Active routes (mpls.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.mpls.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.routes/"
      }
     ]
    },
    {
     "title": "Total routes (mpls.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.mpls.0.routes/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.routes/"
      }
     ]
    },
    {
     "title": "Active routes (inetcolor.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inetcolor.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.routes/"
      }
     ]
    },
    {
     "title": "Total routes (inetcolor.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inetcolor.0.routes/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.routes/"
      }
     ]
    },
    {
     "title": "Active routes (inet6color.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet6color.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.routes/"
      }
     ]
    },
    {
     "title": "Total routes (inet6color.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet6color.0.routes/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.routes/"
      }
     ]
    }
   ]
  },
  {
   "title": "RE PROCESSES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.rpd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.rpd-SIZE/"
      }
     ]
    },
    {
     "title": "RPD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.rpd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RPD-agent SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.rpdagent-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.rpd-SIZE/"
      }
     ]
    },
    {
     "title": "RPD-agent CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.rpdagent-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "EvoAftMan SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.EvoAftManBt-mai-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.EvoAftManBt-mai-SIZE/"
      }
     ]
    },
    {
     "title": "EvoAftMan CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.EvoAftManBt-mai-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SNMPD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.snmpd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.snmpd-SIZE/"
      }
     ]
    },
    {
     "title": "SNMPD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.snmpd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "LACPD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.lacpd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "LACPD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.lacpd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "L2CPD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.l2cpd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "L2CPD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.l2cpd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "JSD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.jsd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "JSD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.jsd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "NA-GRPCD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.grpc-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "NA-GRPCD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.grpc-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "AGENTD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.agentd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "AGENTD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.agentd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "MQTTD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.mqtt-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "MQTTD CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.mqtt-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "MGD-API SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.mgdapi-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "MGD-API CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.mgdapi-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "msvcsd SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.msvcsd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "msvcsd CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.msvcsd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "sysepochman SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.sysepochman-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "sysepochman CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.sysepochman-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "XMLPROXYD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.xmlproxyd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "XMLPROXYD CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.xmlproxyd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "objmon SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.objmon-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "objmon CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.objmon-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "distributord SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.distributord-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "distributord CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.distributord-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ifstatsd SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.ifstatsd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "ifstatsd CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.ifstatsd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "fibd SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.fibd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "fibd CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.fibd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "fibtd SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.fibtd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "fibtd CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.fibtd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ddosd SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value)  from /($host_regex).re.memory.ddosd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    },
    {
     "title": "ddosd CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.ddosd-CPU/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "FPC PROCESSES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "fpc0.memory.evo-cda-bt-size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value)  from /($host_regex).fpc0.memory.evo-cda-bt-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "fpc0.memory.evo-cda-bt-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value)  from /($host_regex).fpc0.memory.evo-cda-bt-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "fpc0.memory.msvcsd-size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value)  from /($host_regex).fpc0.memory.msvcsd-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "fpc0.memory.msvcsd-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).fpc0.memory.msvcsd-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "fpc0.memory.packetio-size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value)  from /($host_regex).fpc0.memory.packetio-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "fpc0.memory.packetio-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).fpc0.memory.packetio-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "fpc0.memory.hwdfpc-size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value)  from /($host_regex).fpc0.memory.hwdfpc-SIZE/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.re.memory.sampled-SIZE/"
    }
   ]
  },
  {
   "title": "fpc0.memory.hwdfpc-CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).fpc0.memory.hwdfpc-CPU/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PFE Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "FPC CPU Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spc-34-ptx1k.fpc.slot0.resource.used-heap-percent",
     "query": "select mean(value) from /($host_regex).fpc.slot.*.resource.used-cpu-percent/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.fpc.slot.*.resource.used-heap-mem-percent/"
    }
   ]
  },
  {
   "title": "FPC Heap Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).fpc.slot.*.resource.used-heap-percent/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.fpc.slot.*.pfe.*.resource.used-ifl-counter-percent/"
    }
   ]
  },
  {
   "title": "FPC Buffer Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).fpc.slot.*.resource.used-buffer-percent/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.fpc.slot.*.pfe.*.resource.used-filter-counter-percent/"
    }
   ]
  },
  { "title": "BGP STATISTICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "bgp peer-count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).protocols.bgp.summary.peer-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.peer-count/"
    }
   ]
  },
  {
   "title": "bgp down-peer-count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).protocols.bgp.summary.down-peer-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.down-peer-count/"
    }
   ]
  },
  { "title": "RSVP statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "RSVP Ingress LSPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).mpls.lsp.Ingress.up-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.group-count/"
    }
   ]
  },
  {
   "title": "RSVP Transit LSPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).mpls.lsp.Transit.up-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.peer-count/"
    }
   ]
  },
  {
   "title": "RSVP Egress LSPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "column": "value",
     "function": "mean",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).mpls.lsp.Egress.up-count/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "/$host_regex.protocols.bgp.summary.peer-count/"
    }
   ]
  }
 ]
}