{
 "title": "JTI - Fabric statistics",
 "tags": [
  "juniper",
  "jti",
  "opennti",
  "streaming"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   },
   { "name": "GroupBy", "query": "1s,10s,30s,1m,5m" },
   {
    "name": "src_type",
    "label": "src_Type 1:SF 2:LC",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.fabricMessageExt\" WITH KEY = \"edges.source_type\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "src_slot",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.fabricMessageExt\" WITH KEY = \"edges.source_slot\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "dest_slot",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.fabricMessageExt\" WITH KEY = \"edges.destination_slot\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "src_pfe",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.fabricMessageExt\" WITH KEY = \"edges.source_pfe\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "dst_pfe",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.fabricMessageExt\" WITH KEY = \"edges.destination_pfe\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "dst_type",
    "label": "dst_Type 1:SF 2:LC",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.fabricMessageExt\" WITH KEY = \"edges.destination_type\"  WHERE  \"device\" =~ /$host_regex/"
   }
  ]
 },
 "panels": [
  {
   "title": "Disclaimer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "content": "**This dashboard has been automatically generated using the dashboard generator of OpenNTI** - It's very easy to personalize it and create your own."
    }
   ]
  },
  {
   "title": "FABRIC traffic stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "FABRIC traffic stats - bytes (delta)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "edges.source_slot" ], "type": "tag" },
        { "params": [ "edges.destination_slot" ], "type": "tag" },
        { "params": [ "edges.source_pfe" ], "type": "tag" },
        { "params": [ "edges.destination_pfe" ], "type": "tag" },
        { "params": [ "edges.source_type" ], "type": "tag" },
        { "params": [ "edges.destination_type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "juniperNetworks.fabricMessageExt",
       "query": "SELECT non_negative_derivative(mean(\"edges.class_stats.transmit_counts.bytes\"), 1s)*8  FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"edges.source_slot\", \"edges.destination_slot\", \"edges.source_pfe\", \"edges.destination_pfe\", \"edges.source_type\", \"edges.destination_type\" fill(null)",
       "select": [
        [
         {
          "params": [
           "edges.class_stats.transmit_counts.bytes"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$host_regex$/" },
        { "condition": "AND", "key": "edges.destination_slot", "operator": "=~", "value": "/^$dest_slot$/" },
        { "condition": "AND", "key": "edges.source_pfe", "operator": "=~", "value": "/^$src_pfe$/" },
        { "condition": "AND", "key": "edges.destination_pfe", "operator": "=~", "value": "/^$dst_pfe$/" },
        { "condition": "AND", "key": "edges.source_slot", "operator": "=~", "value": "/^$src_slot$/" },
        { "condition": "AND", "key": "edges.source_type", "operator": "=~", "value": "/^$src_type$/" },
        { "condition": "AND", "key": "edges.destination_type", "operator": "=~", "value": "/^$dst_type$/" }
       ]
      }
     ]
    },
    {
     "title": "FABRIC traffic stats - packets (delta)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"edges.class_stats.transmit_counts.packets\"), 1s) FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"edges.source_slot\", \"edges.destination_slot\", \"edges.source_pfe\", \"edges.destination_pfe\", \"edges.source_type\", \"edges.destination_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FABRIC traffic stats - Bps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "edges.destination_pfe" ], "type": "tag" },
        { "params": [ "edges.destination_slot" ], "type": "tag" },
        { "params": [ "edges.destination_type" ], "type": "tag" },
        { "params": [ "edges.source_pfe" ], "type": "tag" },
        { "params": [ "edges.source_slot" ], "type": "tag" },
        { "params": [ "edges.source_type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "juniperNetworks.fabricMessageExt",
       "query": "SELECT \"edges.class_stats.transmit_counts.bytes_per_second\" FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY  \"device\", \"edges.destination_pfe\", \"edges.destination_slot\", \"edges.destination_type\", \"edges.source_pfe\", \"edges.source_slot\", \"edges.source_type\" fill(null)",
       "select": [
        [
         {
          "params": [
           "edges.class_stats.transmit_counts.bytes_per_second"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$host_regex$/" },
        { "condition": "AND", "key": "edges.source_type", "operator": "=~", "value": "/^$src_type$/" },
        { "condition": "AND", "key": "edges.source_slot", "operator": "=~", "value": "/^$src_slot$/" },
        { "condition": "AND", "key": "edges.source_pfe", "operator": "=~", "value": "/^$src_pfe$/" },
        { "condition": "AND", "key": "edges.destination_pfe", "operator": "=~", "value": "/^$dst_pfe$/" },
        { "condition": "AND", "key": "edges.destination_slot", "operator": "=~", "value": "/^$dest_slot$/" },
        { "condition": "AND", "key": "edges.destination_type", "operator": "=~", "value": "/^$dst_type$/" }
       ]
      }
     ]
    },
    {
     "title": "FABRIC traffic stats - pps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"edges.class_stats.transmit_counts.packets_per_second\" FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY  \"device\", \"edges.destination_pfe\", \"edges.destination_slot\", \"edges.destination_type\", \"edges.source_pfe\", \"edges.source_slot\", \"edges.source_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FABRIC drop/error stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "FABRIC drop stats - bytes (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"edges.class_stats.transmit_counts.drop_bytes\"), 1s)*8  FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"edges.source_slot\", \"edges.destination_slot\", \"edges.source_pfe\", \"edges.destination_pfe\", \"edges.source_type\", \"edges.destination_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FABRIC drop stats - packets (delta)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"edges.class_stats.transmit_counts.drop_packets\"), 1s) FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"edges.source_slot\", \"edges.destination_slot\", \"edges.source_pfe\", \"edges.destination_pfe\", \"edges.source_type\", \"edges.destination_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FABRIC drops stats - bps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"edges.class_stats.transmit_counts.drop_bytes_per_second\" FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY  \"device\", \"edges.destination_pfe\", \"edges.destination_slot\", \"edges.destination_type\", \"edges.source_pfe\", \"edges.source_slot\", \"edges.source_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FABRIC drops stats - pps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"edges.class_stats.transmit_counts.drop_packets_per_second\" FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY  \"device\", \"edges.destination_pfe\", \"edges.destination_slot\", \"edges.destination_type\", \"edges.source_pfe\", \"edges.source_slot\", \"edges.source_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FABRIC queue stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "FABRIC queue stats - depth (current)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"edges.class_stats.transmit_counts.queue_depth_current\" FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY  \"device\", \"edges.destination_pfe\", \"edges.destination_slot\", \"edges.destination_type\", \"edges.source_pfe\", \"edges.source_slot\", \"edges.source_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FABRIC queue stats - depth (average)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"edges.class_stats.transmit_counts.queue_depth_peak\" FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY  \"device\", \"edges.destination_pfe\", \"edges.destination_slot\", \"edges.destination_type\", \"edges.source_pfe\", \"edges.source_slot\", \"edges.source_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FABRIC queue stats - depth (peak)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-src-type:[[tag_edges.source_type]]-src-slot:[[tag_edges.source_slot]]-src-pfe:[[tag_edges.source_pfe]]-dst-slot:[[tag_edges.destination_slot]]-dst-pfe:[[tag_edges.destination_pfe]]-dst-type[[tag_edges.destination_type]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"edges.class_stats.transmit_counts.queue_depth_peak\" FROM \"juniperNetworks.fabricMessageExt\" WHERE \"device\" =~ /^$host_regex/ AND \"edges.source_type\" =~ /^$src_type$/ AND \"edges.source_slot\" =~ /^$src_slot$/ AND \"edges.source_pfe\" =~ /^$src_pfe$/ AND \"edges.destination_pfe\" =~ /^$dst_pfe$/ AND \"edges.destination_slot\" =~ /^$dest_slot$/ AND \"edges.destination_type\" =~ /^$dst_type$/ AND $timeFilter GROUP BY  \"device\", \"edges.destination_pfe\", \"edges.destination_slot\", \"edges.destination_type\", \"edges.source_pfe\", \"edges.source_slot\", \"edges.source_type\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}