{
 "title": "OC - Firewall Filter",
 "tags": [
  "juniper",
  "opennti",
  "streaming",
  "OC"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "label": "device",
    "query": "SHOW TAG VALUES FROM \"/junos/system/linecard/firewall/\" WITH KEY = \"device\""
   },
   {
    "name": "filter_name",
    "label": "Filter name",
    "query": "SHOW TAG VALUES FROM \"/junos/system/linecard/firewall/\" WITH KEY = \"/junos/firewall/@name\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "counter_name",
    "label": "Counter Name",
    "query": "SHOW TAG VALUES FROM \"/junos/system/linecard/firewall/\" WITH KEY = \"/junos/firewall/state/counter/@name\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "memory_name",
    "label": "Memory Name",
    "query": "SHOW TAG VALUES FROM \"/junos/system/linecard/firewall/\" WITH KEY = \"/junos/firewall/state/memory-usage/@name\"  WHERE \"device\" =~ /$host_regex/"
   }
  ]
 },
 "panels": [
  {
   "title": "Firewall Filters - packets (bps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_/junos/firewall/@name]]-[[tag_/junos/firewall/state/counter/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/junos/firewall/state/counter/bytes\"), 1s) FROM \"/junos/system/linecard/firewall/\" WHERE \"device\" =~ /^$host_regex$/ AND \"/junos/firewall/@name\" =~ /^$filter_name$/ AND \"/junos/firewall/state/counter/@name\" =~ /$counter_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"/junos/firewall/@name\",\"/junos/firewall/state/counter/@name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OC - Firewall Filters - packets (pps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_/junos/firewall/@name]]-[[tag_/junos/firewall/state/counter/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/junos/firewall/state/counter/packets\"), 1s) FROM \"/junos/system/linecard/firewall/\" WHERE \"device\" =~ /^$host_regex$/ AND \"/junos/firewall/@name\" =~ /^$filter_name$/ AND \"/junos/firewall/state/counter/@name\" =~ /$counter_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"/junos/firewall/@name\",\"/junos/firewall/state/counter/@name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Firewall Filters - Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_/junos/firewall/@name]]-[[tag_/junos/firewall/state/memory-usage/@name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"/junos/firewall/state/memory-usage/allocated\" FROM \"/junos/system/linecard/firewall/\" WHERE \"device\" =~ /^$host_regex$/ AND \"/junos/firewall/state/memory-usage/@name\" =~ /^$memory_name$/ AND \"/junos/firewall/@name\" =~ /^$filter_name$/ AND $timeFilter GROUP BY  \"device\", \"/junos/firewall/state/memory-usage/@name\",\"/junos/firewall/@name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}