{
 "title": "JTI - Interface statistics",
 "tags": [
  "juniper",
  "jti",
  "streaming",
  "opennti"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   },
   {
    "name": "if_name",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_interface_ext\" WITH KEY = \"interface_stats.if_name\" WHERE \"device\" =~ /$host_regex/"
   },
   {
    "name": "queue",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_interface_ext\" WITH KEY = \"interface_stats.egress_queue_info.queue_number\" WHERE \"device\" =~ /$host_regex/"
   },
   { "name": "group_by", "query": "1s,10s,30s,1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Interface Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Statistics (pps)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-$col",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "interface_stats.if_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "juniperNetworks.jnpr_interface_ext",
       "query": "SELECT non_negative_derivative(mean(\"interface_stats.ingress_stats.if_pkts\"), 1s) AS \"IN\", non_negative_derivative(mean(\"interface_stats.egress_stats.if_pkts\"), 1s) AS \"OUT\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"interface_stats.if_name\" fill(null)",
       "select": [
        [
         {
          "params": [
           "interface_stats.ingress_stats.if_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.egress_stats.if_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$host_regex/" },
        { "condition": "AND", "key": "interface_stats.if_name", "operator": "=~", "value": "/^$if_name$/" }
       ]
      }
     ]
    },
    {
     "title": "Traffic Statistics(Bps)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"interface_stats.ingress_stats.if_octets\"), 1s)*8 AS \"IN\", non_negative_derivative(mean(\"interface_stats.egress_stats.if_octets\"), 1s) AS \"OUT\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"interface_stats.if_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Traffic Statistics errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "interface_stats.if_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "juniperNetworks.jnpr_interface_ext",
       "query": "SELECT mean(\"interface_stats.egress_stats.if_error\") AS \"out-errors\", mean(\"interface_stats.ingress_errors.if_discards\") AS \"in-discards\", mean(\"interface_stats.ingress_errors.if_errors\") AS \"in-errors\", mean(\"interface_stats.ingress_errors.if_in_fifo_errors\") AS \"in-fifo-errors\", mean(\"interface_stats.ingress_errors.if_in_frame_errors\") AS \"in-frame-errors\", mean(\"interface_stats.ingress_errors.if_in_l2_mismatch_timeouts\") AS \"in-l2-mismatch-timeouts\", mean(\"interface_stats.ingress_errors.if_in_l2chan_errors\") AS \"in-l2chan-errors\", mean(\"interface_stats.ingress_errors.if_in_l3_incompletes\") AS \"in-l3-incompletes\", mean(\"interface_stats.ingress_errors.if_in_qdrops\") AS \"in-qdrops\", mean(\"interface_stats.ingress_errors.if_in_resource_errors\") AS \"in-resource-errors\", mean(\"interface_stats.ingress_errors.if_in_runts\") AS \"in-runts\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"interface_stats.if_name\" fill(null)\"",
       "select": [
        [
         {
          "params": [
           "interface_stats.egress_errors.if_errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "egress-if-errors" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.egress_errors.if_discards"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "egress-if-discard" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-if-errors" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_discards"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "egress-if-discard" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_fifo_errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-fifo-errors" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_frame_errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-frame-errors" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_l2_mismatch_timeouts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-l2-mismatch-timeout" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_l2chan_errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-l2-chan-errors" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_l3_incompletes"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-l3-incomplete" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_qdrops"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-qdrops" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_resource_errors"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-resource-errors" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_errors.if_in_runts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ingress-runt" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$host_regex/" },
        { "condition": "AND", "key": "interface_stats.if_name", "operator": "=~", "value": "/^$if_name$/" }
       ]
      }
     ]
    },
    {
     "title": "Traffic statistics - Unicast/Multicast/Broadcast packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "interface_stats.if_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "juniperNetworks.jnpr_interface_ext",
       "select": [
        [
         {
          "params": [
           "interface_stats.egress_stats.if_uc_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out-unicast" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.egress_stats.if_mc_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out-multicast" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.egress_stats.if_bc_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out-broadcast" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_stats.if_uc_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in-unicast" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_stats.if_mc_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in-multicast" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "interface_stats.ingress_stats.if_bc_pkts"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in-broadcast" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$host_regex/" },
        { "condition": "AND", "key": "interface_stats.if_name", "operator": "=~", "value": "/^$if_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Queue Stats (pps)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-egress-queue:[[tag_interface_stats.egress_queue_info.queue_number]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        {
         "params": [
          "interface_stats.egress_queue_info.queue_number"
         ],
         "type": "tag"
        },
        { "params": [ "interface_stats.if_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "juniperNetworks.jnpr_interface_ext",
       "query": "SELECT non_negative_derivative(mean(\"interface_stats.egress_queue_info.packets\"), 1s) FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND \"interface_stats.egress_queue_info.queue_number\" =~ /^$queue$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"interface_stats.egress_queue_info.queue_number\", \"interface_stats.if_name\" fill(null)",
       "select": [
        [
         {
          "params": [
           "interface_stats.egress_queue_info.packets"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$host_regex/" },
        { "condition": "AND", "key": "interface_stats.if_name", "operator": "=~", "value": "/^$if_name$/" },
        {
         "condition": "AND",
         "key": "interface_stats.egress_queue_info.queue_number",
         "operator": "=~",
         "value": "/^$queue$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Interface Queue Stats (Bps)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-queue:[[tag_interface_stats.egress_queue_info.queue_number]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"interface_stats.egress_queue_info.bytes\"), 1s)*8 FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND \"interface_stats.egress_queue_info.queue_number\" =~ /^$queue$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"interface_stats.egress_queue_info.queue_number\", \"interface_stats.if_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Buffer occupancy (average)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-queue:[[tag_interface_stats.egress_queue_info.queue_number]]",
       "groupBy": [
        { "params": [ "device" ], "type": "tag" },
        {
         "params": [
          "interface_stats.egress_queue_info.queue_number"
         ],
         "type": "tag"
        },
        { "params": [ "interface_stats.if_name" ], "type": "tag" }
       ],
       "measurement": "juniperNetworks.jnpr_interface_ext",
       "query": "SELECT \"interface_stats.egress_queue_info.avg_buffer_occupancy\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND \"interface_stats.egress_queue_info.queue_number\" =~ /^$queue$/ AND $timeFilter GROUP BY \"device\", \"interface_stats.egress_queue_info.queue_number\", \"interface_stats.if_name\"",
       "select": [
        [
         {
          "params": [
           "interface_stats.egress_queue_info.avg_buffer_occupancy"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$host_regex/" },
        { "condition": "AND", "key": "interface_stats.if_name", "operator": "=~", "value": "/^$if_name$/" },
        {
         "condition": "AND",
         "key": "interface_stats.egress_queue_info.queue_number",
         "operator": "=~",
         "value": "/^$queue$/"
        }
       ]
      }
     ]
    },
    {
     "title": "Interface Buffer occupancy (current)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-queue:[[tag_interface_stats.egress_queue_info.queue_number]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"interface_stats.egress_queue_info.cur_buffer_occupancy\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND \"interface_stats.egress_queue_info.queue_number\" =~ /^$queue$/ AND $timeFilter GROUP BY \"device\", \"interface_stats.egress_queue_info.queue_number\", \"interface_stats.if_name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Interface Buffer occupancy (peak)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-queue:[[tag_interface_stats.egress_queue_info.queue_number]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"interface_stats.egress_queue_info.peak_buffer_occupancy\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$host_regex/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND \"interface_stats.egress_queue_info.queue_number\" =~ /^$queue$/ AND $timeFilter GROUP BY \"device\", \"interface_stats.egress_queue_info.queue_number\", \"interface_stats.if_name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}