{
 "title": "JTI - SPRING",
 "description": "Source Packet Routing in Networking",
 "tags": [
  "juniper",
  "opennti",
  "jti",
  "streaming",
  "segment routing"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   },
   {
    "name": "sid",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_sr_stats_per_sid_ext\" WITH KEY = \"sid_stats.sid_identifier\""
   },
   {
    "name": "interface",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_sr_stats_per_if_egress_ext\" WITH KEY = \"per_if_records.if_name\" WHERE \"device\" =~ /$host_regex/"
   },
   { "name": "group_by", "query": "1s,10s,30s,1m,5m" }
  ]
 },
 "panels": [
  { "title": "SPRING Traffic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SPRING Traffic statistics (PPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_per_if_records.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "per_if_records.if_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "juniperNetworks.jnpr_sr_stats_per_if_ingress_ext",
     "query": "SELECT last(\"per_if_records.ingress_stats.packet_rate\") AS \"ingress\" FROM \"juniperNetworks.jnpr_sr_stats_per_if_ingress_ext\" WHERE \"device\" =~ /^$host_regex$/ AND \"per_if_records.if_name\" =~ /^$interface$/ AND $timeFilter GROUP BY time($__interval), \"per_if_records.if_name\", \"device\" fill(null)",
     "select": [
      [
       {
        "params": [
         "per_if_records.ingress_stats.packet_rate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$host_regex$/" },
      { "condition": "AND", "key": "per_if_records.if_name", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "[[tag_device]]-[[tag_per_if_records.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"per_if_records.egress_stats.packet_rate\") AS \"egress\" FROM \"juniperNetworks.jnpr_sr_stats_per_if_egress_ext\" WHERE \"device\" =~ /^$host_regex$/ AND \"per_if_records.if_name\" =~ /^$interface$/ AND $timeFilter GROUP BY time($__interval), \"per_if_records.if_name\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPRING Traffic Statistics(BPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_per_if_records.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"per_if_records.egress_stats.byte_rate\")*8 AS \"egress\" FROM \"juniperNetworks.jnpr_sr_stats_per_if_egress_ext\" WHERE \"device\" =~ /^$host_regex$/ AND \"per_if_records.if_name\" =~ /^$interface$/ AND $timeFilter GROUP BY time($__interval), \"per_if_records.if_name\",\"device\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_device]]-[[tag_per_if_records.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"per_if_records.ingress_stats.byte_rate\")*8 AS \"ingress\" FROM \"juniperNetworks.jnpr_sr_stats_per_if_ingress_ext\" WHERE \"device\" =~ /^$host_regex$/ AND \"per_if_records.if_name\" =~ /^$interface$/ AND $timeFilter GROUP BY time($__interval), \"per_if_records.if_name\",\"device\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SPRING Traffic Stats SID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "SPRING Traffic Statistics per SID (PPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_sid_stats.sid_identifier]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"sid_stats.ingress_stats.packet_rate\") AS \"IN\" FROM \"juniperNetworks.jnpr_sr_stats_per_sid_ext\" WHERE \"device\" =~ /^$host_regex$/  AND \"sid_stats.sid_identifier\" =~ /^$sid$/ AND $timeFilter GROUP BY time($__interval), \"sid_stats.sid_identifier\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPRING Traffic Statistics per SID (BPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_sid_stats.sid_identifier]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"sid_stats.ingress_stats.byte_rate\") AS \"IN\" FROM \"juniperNetworks.jnpr_sr_stats_per_sid_ext\" WHERE \"device\" =~ /^$host_regex$/  AND \"sid_stats.sid_identifier\" =~ /^$sid$/ AND $timeFilter GROUP BY time($__interval), \"sid_stats.sid_identifier\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}